INFO 2024-01-04 23:40:38,302 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-04 23:41:35,558 basehttp 212 "GET / HTTP/1.1" 200 10664
INFO 2024-01-04 23:46:17,500 autoreload 668 Watching for file changes with StatReloader
WARNING 2024-01-04 23:46:31,693 log 241 Not Found: /
WARNING 2024-01-04 23:46:31,693 basehttp 212 "GET / HTTP/1.1" 404 2164
INFO 2024-01-04 23:46:38,254 basehttp 212 "GET /log HTTP/1.1" 301 0
INFO 2024-01-04 23:46:38,259 basehttp 212 "GET /log/ HTTP/1.1" 200 3
INFO 2024-01-04 23:50:21,857 autoreload 668 Watching for file changes with StatReloader
WARNING 2024-01-04 23:50:23,324 log 241 Not Found: /
WARNING 2024-01-04 23:50:23,325 basehttp 212 "GET / HTTP/1.1" 404 2164
INFO 2024-01-04 23:50:29,277 urls 22 user login
WARNING 2024-01-04 23:50:29,277 urls 23 redis don't have enough cache
ERROR 2024-01-04 23:50:29,277 urls 24 record doesn't exist
INFO 2024-01-04 23:50:29,277 basehttp 212 "GET /log/ HTTP/1.1" 200 3
ERROR 2024-01-05 00:01:26,789 exception 124 Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
WARNING 2024-01-05 00:01:26,844 log 241 Bad Request: /
WARNING 2024-01-05 00:01:26,844 basehttp 212 "GET / HTTP/1.1" 400 70366
ERROR 2024-01-05 00:01:27,302 exception 124 Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
WARNING 2024-01-05 00:01:27,320 log 241 Bad Request: /favicon.ico
WARNING 2024-01-05 00:01:27,322 basehttp 212 "GET /favicon.ico HTTP/1.1" 400 70431
INFO 2024-01-05 00:03:20,564 autoreload 668 Watching for file changes with StatReloader
ERROR 2024-01-05 00:03:26,051 exception 124 Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
WARNING 2024-01-05 00:03:26,086 log 241 Bad Request: /
WARNING 2024-01-05 00:03:26,087 basehttp 212 "GET / HTTP/1.1" 400 70557
ERROR 2024-01-05 00:03:26,228 exception 124 Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
WARNING 2024-01-05 00:03:26,249 log 241 Bad Request: /favicon.ico
WARNING 2024-01-05 00:03:26,249 basehttp 212 "GET /favicon.ico HTTP/1.1" 400 70485
ERROR 2024-01-05 00:03:37,064 exception 124 Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
WARNING 2024-01-05 00:03:37,083 log 241 Bad Request: /log
WARNING 2024-01-05 00:03:37,083 basehttp 212 "GET /log HTTP/1.1" 400 70453
ERROR 2024-01-05 00:03:37,235 exception 124 Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\87012\AppData\Local\Programs\Python\Python39\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.sicheng_mall.site:8000'. The domain name provided is not valid according to RFC 1034/1035.
WARNING 2024-01-05 00:03:37,253 log 241 Bad Request: /favicon.ico
WARNING 2024-01-05 00:03:37,254 basehttp 212 "GET /favicon.ico HTTP/1.1" 400 70488
INFO 2024-01-05 00:05:04,017 autoreload 266 F:\test\store_1\store_1\settings.py changed, reloading.
INFO 2024-01-05 00:05:05,011 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-05 00:05:07,160 basehttp 212 code 400, message Bad request version ('\x00\x12\x00\x10\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x00')
ERROR 2024-01-05 00:05:07,161 basehttp 192 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-01-05 00:05:07,175 basehttp 192 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2024-01-05 00:05:07,192 basehttp 212 "GET /log HTTP/1.1" 301 0
INFO 2024-01-05 00:05:07,196 urls 22 user login
WARNING 2024-01-05 00:05:07,196 urls 23 redis don't have enough cache
ERROR 2024-01-05 00:05:07,197 urls 24 record doesn't exist
INFO 2024-01-05 00:05:07,197 basehttp 212 "GET /log/ HTTP/1.1" 200 3
WARNING 2024-01-05 00:05:07,528 log 241 Not Found: /favicon.ico
WARNING 2024-01-05 00:05:07,529 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 2226
INFO 2024-01-07 15:27:00,230 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:27:53,661 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:38:42,108 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:39:29,990 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:41:33,037 autoreload 266 F:\test\store_1\apps\users\apps.py changed, reloading.
INFO 2024-01-07 15:41:33,702 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:41:34,524 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:42:38,276 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:43:48,076 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:46:27,549 autoreload 266 F:\test\store_1\store_1\settings.py changed, reloading.
INFO 2024-01-07 15:46:28,349 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:46:29,160 autoreload 668 Watching for file changes with StatReloader
WARNING 2024-01-07 15:46:32,949 log 241 Not Found: /
WARNING 2024-01-07 15:46:32,950 basehttp 212 "GET / HTTP/1.1" 404 2164
WARNING 2024-01-07 15:46:33,320 log 241 Not Found: /favicon.ico
WARNING 2024-01-07 15:46:33,322 basehttp 212 "GET /favicon.ico HTTP/1.1" 404 2215
INFO 2024-01-07 15:46:39,135 basehttp 212 "GET /log HTTP/1.1" 301 0
INFO 2024-01-07 15:46:39,137 urls 22 user login
WARNING 2024-01-07 15:46:39,137 urls 23 redis don't have enough cache
ERROR 2024-01-07 15:46:39,138 urls 24 record doesn't exist
INFO 2024-01-07 15:46:39,138 basehttp 212 "GET /log/ HTTP/1.1" 200 3
INFO 2024-01-07 15:46:51,189 autoreload 266 F:\test\store_1\store_1\settings.py changed, reloading.
INFO 2024-01-07 15:46:51,829 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:46:52,280 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:46:59,530 autoreload 266 F:\test\store_1\store_1\settings.py changed, reloading.
INFO 2024-01-07 15:47:00,251 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:47:00,565 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:49:33,056 autoreload 266 F:\test\store_1\store_1\settings.py changed, reloading.
INFO 2024-01-07 15:49:33,227 autoreload 266 F:\test\store_1\store_1\settings.py changed, reloading.
INFO 2024-01-07 15:49:33,802 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:49:34,273 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:51:12,771 autoreload 266 F:\test\store_1\apps\users\models.py changed, reloading.
INFO 2024-01-07 15:51:13,426 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:51:14,333 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:51:46,299 autoreload 266 F:\test\store_1\store_1\settings.py changed, reloading.
INFO 2024-01-07 15:51:46,936 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:51:47,617 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:52:47,033 autoreload 266 F:\test\store_1\apps\users\apps.py changed, reloading.
INFO 2024-01-07 15:52:47,748 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:52:48,459 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 15:55:05,776 autoreload 266 F:\test\store_1\store_1\settings.py changed, reloading.
INFO 2024-01-07 15:55:06,516 autoreload 677 Watching for file changes with StatReloader
INFO 2024-01-07 15:55:07,209 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 16:18:56,137 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 16:24:51,434 autoreload 668 Watching for file changes with StatReloader
WARNING 2024-01-07 16:24:56,723 log 241 Not Found: /
WARNING 2024-01-07 16:24:56,724 basehttp 212 "GET / HTTP/1.1" 404 2164
WARNING 2024-01-07 16:24:59,267 log 241 Not Found: /index
WARNING 2024-01-07 16:24:59,268 basehttp 212 "GET /index HTTP/1.1" 404 2197
INFO 2024-01-07 16:25:06,590 basehttp 212 "GET /log HTTP/1.1" 301 0
INFO 2024-01-07 16:25:06,592 urls 22 user login
WARNING 2024-01-07 16:25:06,593 urls 23 redis don't have enough cache
ERROR 2024-01-07 16:25:06,593 urls 24 record doesn't exist
INFO 2024-01-07 16:25:06,594 basehttp 212 "GET /log/ HTTP/1.1" 200 3
INFO 2024-01-07 17:09:02,084 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 17:11:25,523 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 17:11:44,428 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 17:14:30,980 basehttp 212 "GET /usernames/itcast/count HTTP/1.1" 301 0
INFO 2024-01-07 17:14:30,992 basehttp 212 "GET /usernames/itcast/count/ HTTP/1.1" 200 39
INFO 2024-01-07 17:20:40,559 basehttp 212 "GET /usernames/itcast/count/ HTTP/1.1" 200 39
INFO 2024-01-07 17:20:46,720 basehttp 212 "GET /usernames/itcast/count/ HTTP/1.1" 200 39
INFO 2024-01-07 17:27:08,134 autoreload 266 F:\test\store_1\apps\users\views.py changed, reloading.
INFO 2024-01-07 17:27:09,294 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 17:29:01,474 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 17:29:13,020 basehttp 212 "GET /usernames/it/count/ HTTP/1.1" 200 39
INFO 2024-01-07 17:30:04,542 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 17:30:07,091 basehttp 212 "GET /usernames/it/count/ HTTP/1.1" 200 67
INFO 2024-01-07 17:30:42,306 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 17:30:44,354 basehttp 212 "GET /usernames/it/count/ HTTP/1.1" 200 69
INFO 2024-01-07 17:31:03,603 autoreload 668 Watching for file changes with StatReloader
INFO 2024-01-07 17:31:04,375 basehttp 212 "GET /usernames/it/count/ HTTP/1.1" 200 57
INFO 2024-01-07 17:38:53,153 autoreload 266 F:\test\store_1\store_1\urls.py changed, reloading.
INFO 2024-01-07 17:38:54,303 autoreload 668 Watching for file changes with StatReloader
WARNING 2024-01-07 17:38:56,838 log 241 Not Found: /usernames/it/count/
WARNING 2024-01-07 17:38:56,838 basehttp 212 "GET /usernames/it/count/ HTTP/1.1" 404 2324
